apiVersion: v1
kind: Service
metadata:
  name: tomcat-port
  labels:
    app: oms-app
    env: prod
spec:
  selector:
    app: oms-app
  ports:
    # - protocol: TCP
    #   port: 80
    #   targetPort: 80
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-deployment
  labels:
    app: oms-app
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms-app
  template:
    metadata:
      labels:
        app: oms-app
    spec:
      containers:
        - name: tomcat-deploy
          image: chocoman55/tomcat_oms:latest 
          ports:
            - containerPort: 8080
# ---
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: oms-autoscaling
# spec:
#   scaleTargetRef:
#     apiVersion: autoscaling/v2beta1
#     kind: Deployment
#     name: oms-deployment
#   minReplicas: 2
#   maxReplicas: 8
#   metrics:
#   - type: Resource
#     resource: 
#       name: cpu
#       targetAverageUtilization: 75
#   - type: Resource
#     resource:
#       name: memory
#       targetAverageUtilization: 85 